# 日志配置
logrus:
  level: trace
  logFileName: register-go
  filePath: logs/
  #  配置日志切割
  # 30 * 24 * 60 * 60 一个月
  maxAge: 2592000
  # 24 * 60 * 60 一天
  rotationTime: 86400
  formatter: "%time% %level% [%kv%] -- %msg%"
  kv_com: ":"
  field_map_com: " "